apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tridentprovisioners.trident.netapp.io
spec:
  group: trident.netapp.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
  names:
    kind: TridentProvisioner
    listKind: TridentProvisionerList
    plural: tridentprovisioners
    singular: tridentprovisioner
    shortNames:
    - tprov
  scope: Namespaced
